Updates Weight Class
SS13-SCP13/SS13-SCP13 pull request #206
Opened 2018-08-27 02:04 UTC by Affurit

I'm not sure if this makes it difficult to throw or not, I want to say that it will do. May require future work, at least this fixes the major issue.

2018-08-27 02:18 UTC, JakeDaBoss requested changes
Changelog please!

2018-08-27 02:22 UTC, Affurit commented
It's a minor bugfix :(

2018-08-27 02:36 UTC, JakeDaBoss commented
Changelog please!

2018-08-27 03:07 UTC, kachnov approved these changes

2018-08-28 07:48 UTC, JakeDaBoss approved these changes

2018-08-28 07:48 UTC, merged