Archive Changes
SS13-SCP13/SS13-SCP13 pull request #478
Opened 2018-10-04 22:14 UTC by ParnnVuhe

**Archive**
- Replaces the floors.
- Adds a more comprehensive Security System
- Adds a room in the Restricted Archive.
- Does a little cosmetic touchup.
- Adds a little quality of life changes.

Screenshot: https://gyazo.com/13964a8cedacf941980e1d2bf96b97af

2018-10-04 22:40 UTC, JakeDaBoss commented on html/changelogs/pvlog.yml
> +author: ParnnVuhe
Should probably be DoctorOctopus. In-game CKey if you could.

2018-10-05 07:59 UTC, JakeDaBoss requested changes
Awaiting inspection.

2018-10-06 21:13 UTC, ParnnVuhe commented
Closing.. Something pushed the map into a conflict in the two days since its been up.  😐

2018-10-09 07:59 UTC, JakeDaBoss commented
Please present the changes to me in a DM, and the affected map file to make integration into the update smoother.

2018-10-15 11:05 UTC, JakeDaBoss commented
These changes have been reviewed and I don't find them adding much, rather only drawing from the aesthetic currently present.

2018-10-15 11:05 UTC, closed without merging