Cargo Crates Now Work!
SS13-SCP13/SS13-SCP13 pull request #495
Opened 2018-10-11 15:47 UTC by Pandolphina

Makes cargo crates work with access, adds guard gear crate, pistol crate and SMG crate. Removes wizard/witch crate. Cargo should work now, as soon as we get a shuttle.

2018-10-11 19:22 UTC, JakeDaBoss requested changes

2018-10-11 19:22 UTC, JakeDaBoss commented on code/datums/supplypacks/security.dm
> +    contains = list(/obj/item/weapon/gun/projectile/pistol,
Should instead be: /obj/item/weapon/gun/projectile/sec/sec

2018-10-11 19:22 UTC, JakeDaBoss commented on code/datums/supplypacks/security.dm
> +        /obj/item/ammo_magazine/mc9mm = 4,
Should instead be /obj/item/ammo_magazine/c45m

2018-10-11 19:22 UTC, JakeDaBoss commented on code/datums/supplypacks/security.dm
> +    contains = list(/obj/item/clothing/under/solgov/utility/fleet/combat/security,
/obj/item/clothing/under/scp/utility/security

2018-10-11 19:22 UTC, JakeDaBoss commented on code/datums/supplypacks/security.dm
> +                    /obj/item/weapon/cartridge/detective,
PDA cartridge, can be removed.

2018-10-11 19:22 UTC, JakeDaBoss commented on code/datums/supplypacks/supply.dm
> +                    /obj/item/clothing/under/rank/miner,
Can be removed.

2018-10-11 19:22 UTC, JakeDaBoss commented on code/datums/supplypacks/supply.dm
> +                    /obj/item/device/radio/headset/headset_cargo,
Can be removed.

2018-10-11 19:22 UTC, JakeDaBoss commented on code/datums/supplypacks/supply.dm
> +                    /obj/item/weapon/storage/backpack/satchel_eng,
Can be removed.

2018-10-11 19:22 UTC, JakeDaBoss commented on code/datums/supplypacks/supply.dm
> +    contains = list(/obj/item/weapon/storage/backpack/industrial,
Can be removed.

2018-10-11 19:22 UTC, JakeDaBoss commented on code/datums/supplypacks/supply.dm
> +                    /obj/item/clothing/shoes/black,
Can be removed.

2018-10-11 19:50 UTC, Pandolphina commented
Now fixed. Bags/clothes removed, proper clothes/guns added.

2018-10-11 20:22 UTC, JakeDaBoss commented
Does not compile, please check the compile logs.

2018-10-12 07:02 UTC, Pandolphina commented
Should work, soon as you push your guns/clothes to GitHub.

2018-10-15 11:03 UTC, JakeDaBoss commented
Please resolve conflicts, @Pandolphina

2018-10-15 13:07 UTC, Pandolphina commented
The conflicting file is a CHANGELOG. Reee I'll change it in a few hours.

2018-10-15 15:13 UTC, Pandolphina commented
Okay so for whatever reason my local git refuses to pull, push or do anything because of someone elses changelog so I'm just not gonna touch this. Please manually add the file/code thanks.

2018-10-15 15:18 UTC, JakeDaBoss commented
I'm not going through 9 files. That's a monumental waste of my time. Close and re-open.

2018-10-15 15:20 UTC, closed without merging