Removes more mentions of NT and Space.
SS13-SCP13/SS13-SCP13 pull request #522
Opened 2018-10-17 21:04 UTC by Pandolphina

2018-10-18 00:49 UTC, rhicora approved these changes

2018-10-18 07:02 UTC, JakeDaBoss requested changes

2018-10-18 07:02 UTC, JakeDaBoss commented on code/game/objects/items/devices/geiger.dm
> +	description_fluff = "For decades counters have been saving the lives of unsuspecting laborers and technicians. You can never be too careful around radiation."
You forgot the geiger.

2018-10-19 14:45 UTC, JakeDaBoss approved these changes

2018-10-19 14:45 UTC, merged