Makes SCPs equal in move speed to players.
SS13-SCP13/SS13-SCP13 pull request #533
Opened 2018-10-18 23:46 UTC by JarlElbow

2018-10-19 00:50 UTC, kachnov commented
I think they should be slightly faster, otherwise they won't ever catch anybody.

2018-10-19 05:27 UTC, rhicora commented
For this weekend, we're doing an equal-speed test and seeing if it feels okay. It's very possible @kachnov is right, in which case we can make humans tire out after extended running.

2018-10-19 05:27 UTC, rhicora approved these changes

2018-10-19 07:32 UTC, UndeadNappist commented
Kachnov is half-right since different players act and move at different speeds inconsistently, even though there's no good reason.

On the other hand, for some SCPs - those with minions, instant transportation and/or an effective deathtouch - them being slower then players might be a good idea if you assume they have some good way of cornering them.

I strongly suspect for speed testing if the SCPs are NPC controlled they should be faster, but on PC control should be slower, even though that's arbitrary.

2018-10-22 15:04 UTC, JakeDaBoss requested changes

2018-10-22 15:04 UTC, JakeDaBoss commented on code/modules/SCP/SCPs/SCP-049.dm
> +		walk_to(src, target, 1, config.run_speed)
Alright, after serious consideration, I'm not going to merge this on SCP's being the same speed as humans. They might not have been in CB, but this is SS13. Balance is everything. I agree 0.9, almost an entire point, faster is too much, but we should see what it does on 0.2 first. If you could make SCP-106 that as well, please.

0.2 looks like a good starting point to nerf or buff further based on results, but to my understanding, 0.2 will give people a fighting chance to run and use airlocks to their advantage.

2018-10-26 18:33 UTC, JarlElbow commented
Fixed

2018-10-26 20:26 UTC, JakeDaBoss approved these changes

2018-10-26 20:26 UTC, merged